title: The Beautiful Octi Theme
description: Cool Theme for Jekyll with Monospaced Fonts and Cute Colors
theme: octi

exclude:
  - ".idea/"

permalink: /posts/:title/

socials:
  twitter: ItsLemonChan
  twitch: itslemonchan
  github: justalemon
  gitlab: itslemonchan
  youtube_channel: UCEOwsaYl9b_oJ9VPnpFSfcg
  # youtube_username: "" # for channels like @LinusTechTips

collections:
  projects:
    output: true
