title: The Beautiful Octi Theme
description: Cool Theme for Jekyll with Monospaced Fonts and Cute Colors
theme: octi

exclude:
  - ".idea/"

projects:
  - name: "LemonUI for .NET"
    image: "lemonui.png"
    category:
      commission: false
      foss: true
    description: "LemonUI for .NET is a library for creating different types of user interfaces in Grand Theft Auto V via modding frameworks that use .NET Framework or .NET Core (ScriptHookVDotNet, RagePluginHook, RageMP and FiveM)."
    urls:
      "GitHub": "https://github.com/LemonUIbyLemon/LemonUI"
      "5mods": "https://www.gta5-mods.com/tools/lemonui"
      "cfx.re Forums": "https://forum.cfx.re/t/1492419"
      "NuGet Package (FiveM)": "https://www.nuget.org/packages/LemonUI.FiveM/"
      "NuGet Package (RageMP)": "https://www.nuget.org/packages/LemonUI.RageMP/"
      "NuGet Package (RagePluginHook)": "https://www.nuget.org/packages/LemonUI.RagePluginHook/"
      "NuGet Package (ScriptHookVDotNet3)": "https://www.nuget.org/packages/LemonUI.SHVDN3/"
