name: Main
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  # releases
  contents: write
  # ghcr.io
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ruby/setup-ruby@v1.161.0
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - uses: justalemon/VersionPatcher@v0.7.2
        with:
          version: 0.0.1.alpha.${{ github.run_number }}
          gemspec-files: "*.gemspec"
      - run: gem build
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}
          path: "*.gem"
          if-no-files-found: error
  ghcr:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ github.event.repository.name }}
          path: .
      - run: gem push --host https://${{ github.repository_owner }}:${{ github.token }}@rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ruby/setup-ruby@v1.161.0
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: "_site"
