name: Main
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  # pages
  pages: write
  # releases
  contents: write
  # ghcr.io
  packages: write
  # idk what this is but actions/deploy-pages needs it
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: "10"
          run_install: false
          standalone: true
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: "22.x"
          cache: pnpm
      - uses: ruby/setup-ruby@v1.229.0
        with:
          ruby-version: "3.3.6"
      - uses: justalemon/VersionPatcher@v0.8
        with:
          version: 0.0.1.alpha.${{ github.run_number }}
          gemspec-files: "*.gemspec"
      - run: pnpm install
      - run: pnpm build
      - run: gem build
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ github.event.repository.name }}
          path: "*.gem"
          if-no-files-found: error
  ghcr:
    runs-on: ubuntu-22.04
    needs:
      - build
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}
          path: .
      - run: "mkdir -p ~/.gem && printf -- '---\n:github: ${{ github.token }}\n' > ~/.gem/credentials && chmod 0600 ~/.gem/credentials"
      - run: gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
  deploy:
    runs-on: ubuntu-22.04
    needs:
      - build
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: ruby/setup-ruby@v1.229.0
        with:
          ruby-version: "3.3.6"
      - uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ github.event.repository.name }}
          path: .
      - run: gem install *.gem
      - run: jekyll build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "_site"
      - uses: actions/deploy-pages@v4.0.5
